// Seed vendor data — swap this file's export for an API call in vendorService.
// All 30 vendors are defined here so appConfig stays under 50 lines.

export const ALL_VENDORS = [
  {
    id: 1,
    name: "Kuy Teav Sor Brorng",
    cuisine: "Noodles",
    price_range: 1,
    rating: 4.8,
    wait_time_est: 5,
    lat: 11.568,
    lng: 104.9172,
    photo_url:
      "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&h=500&fit=crop",
    description:
      "Classic Phnom Penh–style clear pork broth simmering since 4am.",
    open_now: true,
    hours: "06:00 – 13:00",
    address: "Street 182, near Central Market",
    menu: [
      {
        name: "Kuy Teav Sor (Small)",
        price: 1.5,
        desc: "Clear pork broth, rice noodles",
        category: "Main",
      },
      { name: "Kuy Teav Sor (Large)", price: 2.0, category: "Main" },
      { name: "Fried Dough Stick", price: 0.75, category: "Sides" },
      { name: "Iced Jasmine Tea", price: 0.5, category: "Drinks" },
    ],
  },
  {
    id: 2,
    name: "Num Banh Chok Neang Srey",
    cuisine: "Khmer",
    price_range: 1,
    rating: 4.7,
    wait_time_est: 4,
    lat: 11.5665,
    lng: 104.9165,
    photo_url:
      "https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&h=500&fit=crop",
    description:
      "Authentic Khmer rice noodles with lemongrass coconut fish gravy. Sold out by 10am.",
    open_now: true,
    hours: "06:30 – 10:30",
    address: "Street 184, Daun Penh",
    menu: [
      { name: "Num Banh Chok (Regular)", price: 1.25, category: "Main" },
      { name: "Num Banh Chok + Extra Herbs", price: 1.75, category: "Main" },
      { name: "Palm Sugar Iced Tea", price: 0.75, category: "Drinks" },
    ],
  },
  {
    id: 3,
    name: "Bai Sach Chrouk — Lok Ta Pov",
    cuisine: "Rice",
    price_range: 1,
    rating: 4.9,
    wait_time_est: 3,
    lat: 11.5648,
    lng: 104.9182,
    photo_url:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=500&fit=crop",
    description:
      "Charcoal-grilled coconut pork over jasmine rice with pickled daikon.",
    open_now: true,
    hours: "05:30 – 10:30",
    address: "Monivong Blvd, corner St 178",
    menu: [
      { name: "Bai Sach Chrouk (Standard)", price: 1.25, category: "Main" },
      { name: "Bai Sach Chrouk (Double Pork)", price: 1.75, category: "Main" },
      { name: "Add Fried Egg", price: 0.5, category: "Add-ons" },
      { name: "Hot Ginger Tea", price: 0.5, category: "Drinks" },
    ],
  },
  {
    id: 4,
    name: "Banh Mi 222",
    cuisine: "Banh Mi",
    price_range: 1,
    rating: 4.6,
    wait_time_est: 4,
    lat: 11.5638,
    lng: 104.916,
    photo_url:
      "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&h=500&fit=crop",
    description:
      "Crispy French baguette with pâté, cold cuts, pickled carrot, and house chilli.",
    open_now: true,
    hours: "06:00 – 18:00",
    address: "Street 222, BKK1",
    menu: [
      { name: "Banh Mi Classic", price: 1.0, category: "Main" },
      { name: "Banh Mi Chicken", price: 1.5, category: "Main" },
      { name: "Banh Mi Egg + Cheese", price: 1.25, category: "Main" },
      { name: "Iced Cambodian Coffee", price: 1.0, category: "Drinks" },
    ],
  },
  {
    id: 5,
    name: "Cha Houy Teuk Phkar Chann",
    cuisine: "Dessert",
    price_range: 1,
    rating: 4.9,
    wait_time_est: 3,
    lat: 11.5625,
    lng: 104.9175,
    photo_url:
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&h=500&fit=crop",
    description:
      "Traditional Khmer sweet jellies in coconut milk — tapioca, grass jelly, taro on crushed ice.",
    open_now: true,
    hours: "10:00 – 20:00",
    address: "Street 135, Tonle Bassac",
    menu: [
      { name: "Cha Houy Teuk (Mixed)", price: 1.0, category: "Main" },
      { name: "Taro & Coconut Pudding", price: 1.25, category: "Main" },
      { name: "Mango Sticky Rice", price: 1.5, category: "Main" },
    ],
  },
  {
    id: 6,
    name: "Hu Tieu Nam Vang",
    cuisine: "Noodles",
    price_range: 2,
    rating: 4.6,
    wait_time_est: 8,
    lat: 11.5612,
    lng: 104.9188,
    photo_url:
      "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&h=500&fit=crop",
    description:
      "Vietnamese-Cambodian noodle soup with pork, shrimp, quail egg, crispy shallots.",
    open_now: true,
    hours: "07:00 – 21:00",
    address: "Street 130, near Independence Monument",
    menu: [
      { name: "Hu Tieu (Regular)", price: 2.5, category: "Main" },
      { name: "Hu Tieu Seafood", price: 3.5, category: "Main" },
      { name: "Iced Barley Tea", price: 0.75, category: "Drinks" },
    ],
  },
  {
    id: 7,
    name: "Ang Sach Ko — Charcoal Beef",
    cuisine: "BBQ",
    price_range: 2,
    rating: 4.5,
    wait_time_est: 10,
    lat: 11.56,
    lng: 104.9163,
    photo_url:
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=500&fit=crop",
    description:
      "Beef skewers marinated in lemongrass, garlic, and fish sauce, grilled to order.",
    open_now: true,
    hours: "11:00 – 22:00",
    address: "Street 155, BKK1 area",
    menu: [
      { name: "Beef Skewer (×3)", price: 2.0, category: "Main" },
      { name: "Pork Skewer (×3)", price: 1.75, category: "Main" },
      { name: "Chicken Wing (×2)", price: 2.0, category: "Main" },
      { name: "Papaya Salad", price: 1.5, category: "Sides" },
    ],
  },
  {
    id: 8,
    name: "Nom Pang Kaya Stall",
    cuisine: "Banh Mi",
    price_range: 1,
    rating: 4.5,
    wait_time_est: 2,
    lat: 11.5592,
    lng: 104.917,
    photo_url:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
    description: "Cambodian coconut jam on fresh toasted baguette.",
    open_now: true,
    hours: "06:00 – 12:00",
    address: "Street 163, Daun Penh",
    menu: [
      { name: "Nom Pang Kaya", price: 0.5, category: "Main" },
      {
        name: "Nom Pang Butter + Condensed Milk",
        price: 0.5,
        category: "Main",
      },
      { name: "Nom Pang Egg (Fried)", price: 0.75, category: "Main" },
    ],
  },
  {
    id: 9,
    name: "Beef Ho Fun — Uncle Chen",
    cuisine: "Chinese",
    price_range: 2,
    rating: 4.4,
    wait_time_est: 9,
    lat: 11.5583,
    lng: 104.9185,
    photo_url:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=500&fit=crop",
    description:
      "Wide flat rice noodles stir-fried in a screaming-hot wok with beef and dark soy.",
    open_now: false,
    hours: "11:00 – 21:00",
    address: "Street 136, Phsar Kandal area",
    menu: [
      { name: "Dry Beef Ho Fun", price: 2.5, category: "Main" },
      { name: "Soup Beef Ho Fun", price: 2.5, category: "Main" },
      { name: "Iced Chrysanthemum Tea", price: 0.75, category: "Drinks" },
    ],
  },
  {
    id: 10,
    name: "Bot Bor Sach Chrouk",
    cuisine: "Rice",
    price_range: 1,
    rating: 4.8,
    wait_time_est: 5,
    lat: 11.5575,
    lng: 104.9178,
    photo_url:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=500&fit=crop",
    description:
      "Silky rice congee with shredded pork, ginger, spring onion, and century egg.",
    open_now: true,
    hours: "05:30 – 11:00",
    address: "Street 178, near Monivong Blvd",
    menu: [
      { name: "Bot Bor Pork (Small)", price: 1.0, category: "Main" },
      { name: "Bot Bor Pork (Large)", price: 1.5, category: "Main" },
      { name: "Bot Bor Chicken", price: 1.75, category: "Main" },
    ],
  },
  {
    id: 11,
    name: "Lok Lak — Neak Ta Stall",
    cuisine: "Khmer",
    price_range: 2,
    rating: 4.6,
    wait_time_est: 8,
    lat: 11.5568,
    lng: 104.9163,
    photo_url:
      "https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&h=500&fit=crop",
    description:
      "Wok-tossed beef cubes in oyster-lime sauce with kampot pepper dip.",
    open_now: true,
    hours: "10:30 – 22:00",
    address: "Street 432, Toul Tom Poung",
    menu: [
      { name: "Lok Lak Beef", price: 3.5, category: "Main" },
      { name: "Lok Lak Chicken", price: 3.0, category: "Main" },
      { name: "Extra Kampot Pepper Sauce", price: 0.5, category: "Add-ons" },
    ],
  },
  {
    id: 12,
    name: "Teuk Tnaot Palm Juice Cart",
    cuisine: "Drinks",
    price_range: 1,
    rating: 4.7,
    wait_time_est: 2,
    lat: 11.5558,
    lng: 104.919,
    photo_url:
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=500&fit=crop",
    description:
      "Fresh palm tree juice delivered from Kandal Province farms at dawn.",
    open_now: true,
    hours: "07:00 – 19:00",
    address: "Street 143, Olympic Stadium area",
    menu: [
      { name: "Fresh Palm Juice (Small)", price: 0.75, category: "Drinks" },
      { name: "Iced Palm Sugar Drink", price: 1.0, category: "Drinks" },
      { name: "Palm + Coconut Water Mix", price: 1.25, category: "Drinks" },
    ],
  },
  {
    id: 13,
    name: "Banan Chien (Fried Banana)",
    cuisine: "Dessert",
    price_range: 1,
    rating: 4.6,
    wait_time_est: 3,
    lat: 11.555,
    lng: 104.9168,
    photo_url:
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&h=500&fit=crop",
    description:
      "Crispy battered bananas and taro fried in palm oil, golden and caramelised.",
    open_now: true,
    hours: "14:00 – 22:00",
    address: "Street 155, near Olympic Stadium",
    menu: [
      { name: "Fried Banana (×5)", price: 1.0, category: "Main" },
      { name: "Fried Taro (×5)", price: 1.0, category: "Main" },
      { name: "Mixed Platter (×10)", price: 1.75, category: "Main" },
    ],
  },
  {
    id: 14,
    name: "Mee Cha Wok Station",
    cuisine: "Noodles",
    price_range: 2,
    rating: 4.4,
    wait_time_est: 7,
    lat: 11.5543,
    lng: 104.918,
    photo_url:
      "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&h=500&fit=crop",
    description:
      "Stir-fried egg noodles with protein, wok-charred vegetables, and dark soy.",
    open_now: true,
    hours: "10:00 – 21:00",
    address: "Street 450, Toul Tom Poung",
    menu: [
      { name: "Mee Cha Pork", price: 2.0, category: "Main" },
      { name: "Mee Cha Seafood", price: 2.75, category: "Main" },
      { name: "Mee Cha Vegetable", price: 1.75, category: "Main" },
    ],
  },
  {
    id: 15,
    name: "Fresh Spring Roll Corner",
    cuisine: "Khmer",
    price_range: 1,
    rating: 4.9,
    wait_time_est: 4,
    lat: 11.5535,
    lng: 104.9163,
    photo_url:
      "https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&h=500&fit=crop",
    description:
      "Handrolled fresh spring rolls with shrimp, pork, jicama, and herbs.",
    open_now: true,
    hours: "09:00 – 18:00",
    address: "Street 155, Russian Market area",
    menu: [
      { name: "Fresh Rolls (×3)", price: 2.0, category: "Main" },
      { name: "Fresh Rolls (×6)", price: 3.75, category: "Main" },
      { name: "Fried Rolls (×4)", price: 2.25, category: "Main" },
    ],
  },
  {
    id: 16,
    name: "Samlar Machu Yuon Soup",
    cuisine: "Khmer",
    price_range: 2,
    rating: 4.6,
    wait_time_est: 8,
    lat: 11.5528,
    lng: 104.9185,
    photo_url:
      "https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&h=500&fit=crop",
    description:
      "Sour Khmer tamarind broth with fish, tomato, pineapple, and water spinach.",
    open_now: true,
    hours: "10:00 – 21:30",
    address: "Street 440, Toul Tom Poung",
    menu: [
      { name: "Samlar Machu (Fish)", price: 2.5, category: "Main" },
      { name: "Samlar Machu (Shrimp)", price: 3.0, category: "Main" },
      { name: "Steamed Rice", price: 0.5, category: "Sides" },
    ],
  },
  {
    id: 17,
    name: "Sach Ko Ang — Overnight Marinated",
    cuisine: "BBQ",
    price_range: 2,
    rating: 4.7,
    wait_time_est: 10,
    lat: 11.552,
    lng: 104.9172,
    photo_url:
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=500&fit=crop",
    description:
      "Premium beef marinated overnight in fish sauce and lemongrass, grilled over hardwood charcoal.",
    open_now: true,
    hours: "17:00 – 23:00",
    address: "Street 460, Toul Tom Poung",
    menu: [
      { name: "Beef Skewer Set (×4)", price: 3.0, category: "Main" },
      { name: "Pork Neck Set (×2)", price: 2.5, category: "Main" },
      { name: "Sticky Rice", price: 0.75, category: "Sides" },
    ],
  },
  {
    id: 18,
    name: "Cha Gio Vietnamese Roll Stall",
    cuisine: "Banh Mi",
    price_range: 1,
    rating: 4.5,
    wait_time_est: 5,
    lat: 11.5512,
    lng: 104.9162,
    photo_url:
      "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&h=500&fit=crop",
    description:
      "Crispy fried Vietnamese rolls packed with pork, glass noodles, and black pepper.",
    open_now: true,
    hours: "10:00 – 20:00",
    address: "Street 155, Toul Tom Poung",
    menu: [
      { name: "Cha Gio (×4)", price: 1.75, category: "Main" },
      { name: "Cha Gio + Rice Plate", price: 2.5, category: "Main" },
      { name: "Iced Lemon Tea", price: 0.75, category: "Drinks" },
    ],
  },
  {
    id: 19,
    name: "Num Kachay (Chive Cake)",
    cuisine: "Khmer",
    price_range: 1,
    rating: 4.6,
    wait_time_est: 3,
    lat: 11.5503,
    lng: 104.918,
    photo_url:
      "https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&h=500&fit=crop",
    description:
      "Pan-fried Khmer chive and rice flour cakes — crispy outside, chewy inside.",
    open_now: false,
    hours: "06:30 – 12:00",
    address: "Russian Market lane, Toul Tom Poung",
    menu: [
      { name: "Num Kachay (×3)", price: 0.75, category: "Main" },
      { name: "Num Kachay (×6)", price: 1.5, category: "Main" },
      { name: "Sweet Chilli Sauce", price: 0.25, category: "Add-ons" },
    ],
  },
  {
    id: 20,
    name: "Cà Phê Phin — Vietnamese Coffee",
    cuisine: "Drinks",
    price_range: 1,
    rating: 4.8,
    wait_time_est: 4,
    lat: 11.5495,
    lng: 104.917,
    photo_url:
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=500&fit=crop",
    description:
      "Vietnamese drip coffee through a phin filter over sweetened condensed milk.",
    open_now: true,
    hours: "06:00 – 18:00",
    address: "Street 432, Russian Market",
    menu: [
      { name: "Cà Phê Đen (Hot)", price: 1.0, category: "Drinks" },
      { name: "Cà Phê Sữa Đá (Iced)", price: 1.25, category: "Drinks" },
      { name: "Bạc Xỉu (White Coffee)", price: 1.25, category: "Drinks" },
    ],
  },
  {
    id: 21,
    name: "Mango Sticky Rice Cart",
    cuisine: "Dessert",
    price_range: 1,
    rating: 4.9,
    wait_time_est: 2,
    lat: 11.5488,
    lng: 104.9183,
    photo_url:
      "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&h=500&fit=crop",
    description:
      "Sweet glutinous rice in thick coconut cream with fresh Kampot mango slices.",
    open_now: true,
    hours: "11:00 – 20:00",
    address: "Russian Market entrance, Toul Tom Poung",
    menu: [
      { name: "Mango Sticky Rice (Regular)", price: 2.0, category: "Main" },
      { name: "Mango Sticky Rice (Large)", price: 3.0, category: "Main" },
      { name: "Black Sesame Coconut Rice", price: 1.75, category: "Main" },
    ],
  },
  {
    id: 22,
    name: "Poat Ang (Grilled Corn)",
    cuisine: "BBQ",
    price_range: 1,
    rating: 4.7,
    wait_time_est: 4,
    lat: 11.5478,
    lng: 104.9163,
    photo_url:
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=500&fit=crop",
    description:
      "Fresh sweetcorn grilled over charcoal and brushed with coconut-butter glaze.",
    open_now: true,
    hours: "15:00 – 22:00",
    address: "Street 163, near Russian Market",
    menu: [
      { name: "Grilled Corn (×1)", price: 0.75, category: "Main" },
      { name: "Grilled Corn (×3)", price: 2.0, category: "Main" },
      { name: "Coconut-Glazed Corn", price: 1.0, category: "Main" },
    ],
  },
  {
    id: 23,
    name: "Tom Yum Spice Station",
    cuisine: "Chinese",
    price_range: 2,
    rating: 4.3,
    wait_time_est: 10,
    lat: 11.547,
    lng: 104.9175,
    photo_url:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=500&fit=crop",
    description:
      "Hot sour soup with lemongrass, kaffir lime, galangal, and seafood or chicken.",
    open_now: true,
    hours: "11:00 – 22:00",
    address: "Street 450, Toul Tom Poung",
    menu: [
      { name: "Tom Yum Shrimp", price: 3.0, category: "Main" },
      { name: "Tom Yum Chicken", price: 2.5, category: "Main" },
      { name: "Tom Yum Seafood Mix", price: 4.0, category: "Main" },
    ],
  },
  {
    id: 24,
    name: "Fish Amok — Aunt Sopheap",
    cuisine: "Khmer",
    price_range: 2,
    rating: 4.7,
    wait_time_est: 8,
    lat: 11.5462,
    lng: 104.9165,
    photo_url:
      "https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&h=500&fit=crop",
    description:
      "Fish amok steamed in banana leaf — thick coconut curry mousse with kaffir lime.",
    open_now: true,
    hours: "10:00 – 21:00",
    address: "Street 163, Russian Market",
    menu: [
      { name: "Fish Amok + Rice", price: 3.0, category: "Main" },
      { name: "Chicken Amok + Rice", price: 2.75, category: "Main" },
      { name: "Tofu Amok + Rice", price: 2.25, category: "Main" },
    ],
  },
  {
    id: 25,
    name: "Banh Cuon Rice Roll Shop",
    cuisine: "Chinese",
    price_range: 2,
    rating: 4.4,
    wait_time_est: 7,
    lat: 11.5455,
    lng: 104.9182,
    photo_url:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=500&fit=crop",
    description:
      "Steamed rice flour rolls filled with pork and wood-ear mushroom. Topped with crispy shallot.",
    open_now: true,
    hours: "07:00 – 15:00",
    address: "Street 155, near Russian Market",
    menu: [
      { name: "Banh Cuon (×4 rolls)", price: 2.25, category: "Main" },
      { name: "Banh Cuon + Cha Lua Sausage", price: 3.0, category: "Main" },
      { name: "Extra Dipping Sauce", price: 0.25, category: "Add-ons" },
    ],
  },
  {
    id: 26,
    name: "Apsara Khmer Set Lunch",
    cuisine: "Khmer",
    price_range: 3,
    rating: 4.5,
    wait_time_est: 12,
    lat: 11.563,
    lng: 104.9197,
    photo_url:
      "https://images.unsplash.com/photo-1562802378-063ec186a863?w=800&h=500&fit=crop",
    description:
      "Three-dish lunch set that changes daily. Generous portions for office workers.",
    open_now: true,
    hours: "10:00 – 22:00",
    address: "Norodom Blvd, BKK1",
    menu: [
      { name: "3-Dish Lunch Set + Rice", price: 5.0, category: "Main" },
      { name: "Lap Khmer (Beef Salad)", price: 4.5, category: "Main" },
      { name: "Amok Platter", price: 6.0, category: "Main" },
    ],
  },
  {
    id: 27,
    name: "Angkor Noodle House",
    cuisine: "Noodles",
    price_range: 2,
    rating: 4.5,
    wait_time_est: 9,
    lat: 11.554,
    lng: 104.9158,
    photo_url:
      "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=800&h=500&fit=crop",
    description:
      "Kuay chap — flat rice sheets in five-spice dark broth with pork belly and hard-boiled egg.",
    open_now: true,
    hours: "07:00 – 20:00",
    address: "Street 143, Olympic Stadium area",
    menu: [
      { name: "Kuay Chap (Soup)", price: 2.25, category: "Main" },
      { name: "Dry Noodles + Pork Belly", price: 2.0, category: "Main" },
      { name: "Pork Rib Broth (Extra)", price: 1.0, category: "Add-ons" },
    ],
  },
  {
    id: 28,
    name: "Night Market Satay Stand",
    cuisine: "BBQ",
    price_range: 2,
    rating: 4.6,
    wait_time_est: 8,
    lat: 11.5475,
    lng: 104.9195,
    photo_url:
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=500&fit=crop",
    description:
      "Satay skewers with peanut sauce and cucumber relish. Best after 6pm.",
    open_now: false,
    hours: "18:00 – 01:00",
    address: "Street 440, Toul Tom Poung",
    menu: [
      { name: "Chicken Satay (×4)", price: 2.5, category: "Main" },
      { name: "Pork Satay (×4)", price: 2.25, category: "Main" },
      { name: "Mixed Satay (×6)", price: 3.5, category: "Main" },
    ],
  },
  {
    id: 29,
    name: "Iced Tea & Bubble Corner",
    cuisine: "Drinks",
    price_range: 1,
    rating: 4.6,
    wait_time_est: 5,
    lat: 11.5507,
    lng: 104.9162,
    photo_url:
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=500&fit=crop",
    description:
      "Freshly brewed iced teas, lime soda, and house bubble tea with tapioca pearls.",
    open_now: true,
    hours: "09:00 – 21:00",
    address: "Street 155, Toul Tom Poung",
    menu: [
      { name: "Iced Lemon Grass Tea", price: 0.75, category: "Drinks" },
      { name: "Taro Bubble Tea", price: 1.5, category: "Drinks" },
      { name: "Brown Sugar Milk Tea", price: 1.75, category: "Drinks" },
      { name: "Fresh Lime Soda", price: 1.0, category: "Drinks" },
    ],
  },
  {
    id: 30,
    name: "Mama's Rice & Curry Stall",
    cuisine: "Rice",
    price_range: 1,
    rating: 4.8,
    wait_time_est: 6,
    lat: 11.556,
    lng: 104.9196,
    photo_url:
      "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=500&fit=crop",
    description:
      "Point-and-pick stall with 8+ rotating Khmer curries daily. Students' go-to since 2015.",
    open_now: true,
    hours: "10:30 – 14:30",
    address: "Street 450, near Olympic area",
    menu: [
      { name: "Rice + 2 Dishes", price: 1.5, category: "Main" },
      { name: "Rice + 4 Dishes", price: 2.0, category: "Main" },
      { name: "Extra Steamed Rice", price: 0.25, category: "Add-ons" },
    ],
  },
];
